---
- hosts: all

  vars_files:
    - vars.yml

  tasks:

    - name: "Create development environment"
      ansible.builtin.file:
        path: "~/development/{{ item }}"
        state: directory
      with_items: "{{ dev_env_needs }}"
      become: false
    
    - import_tasks: tasks/modify_sudoers.yml
      when: allow_admin_nopasswd_sudo
      become: true

    - import_tasks: tasks/configure_dotfiles.yml
      when: configure_dotfiles_from_repo
      become: false