---
- hosts: all

  vars_files:
    - vars.yml

  tasks:
    - import_tasks: tasks/modify_sudoers.yml
      when: allow_admin_nopasswd_sudo

    - import_tasks: tasks/configure_dotfiles.yml
      when: configure_dotfiles_from_repo 