---

- name: Clone dotfiles repo from Git
  ansible.builtin.git:
    repo: "{{  dotfiles_repo }}"
    dest: "{{  dotfiles_destination }}"

- name: "Remove existing .zprofile"
  ansible.builtin.file:
    path: ~/.zprofile
    state: absent

- name: "Set symlink for each dotfile"
  ansible.builtin.file:
    src: "{{  dotfiles_destination }}/{{ item }}"
    path: '~/.{{ item }}'
    state: link
  with_items:
    - "{{ dotfiles_to_link }}"