---

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Install requested casks
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  with_items: "{{ homebrew_cask_packages }}"